config/routes.rb
Spree::Core::Engine.routes.draw do

  # Search routes
  get 's/*product_group_query', :to => 'products#index', :as => :simple_search
  get '/pg/:product_group_name', :to => 'products#index', :as => :pg_search
  get '/t/*id/s/*product_group_query', :to => 'taxons#show', :as => :taxons_search
  get 't/*id/pg/:product_group_name', :to => 'taxons#show', :as => :taxons_pg_search

  namespace :admin do
    resources :product_groups do
      resources :product_scopes
    end
  end

end

app/models/spree/product_group.rb
# *ProductGroups* are used for creating and managing sets of products.
# Product group can be either anonymous(adhoc) or named.
#
# Anonymous Product groups are created by combining product scopes generated from url
# in 2 formats:
#
#   /t/*taxons/s/name_of_scope/comma_separated_arguments/name_of_scope_that_doesn_take_any//order
#   */s/name_of_scope/comma_separated_arguments/name_of_scope_that_doesn_take_any//order
#
# Named product groups can be created from anonymous ones, lub from another named scope
# (using ProductGroup.from_url method).
# Named product groups have pernament urls, that don't change even after changes
# to scopes are made, and come in two types.
#
#   /t/*taxons/pg/named_product_group
#   */pg/named_product_group
#
# first one is used for combining named scope with taxons, named product group can
# have #in_taxon or #taxons_name_eq scope defined, result should combine both
# and return products that exist in both taxons.
#
# ProductGroup#dynamic_products returns chain of named scopes generated from order and
# product scopes. So you can do counting, calculations etc, on resulted set of products,
# without retriving all records.
#
# ProductGroup operates on named scopes defined for product in Scopes::Product,
# or generated automatically by meta_search
#
module Spree
  class ProductGroup < ActiveRecord::Base
    validates :name, :permalink, :presence => true
    validates_associated :product_scopes

    after_save :update_memberships

    has_and_belongs_to_many :cached_products, :class_name => 'Spree::Product',
                                              :join_table => 'spree_product_groups_products'
    has_many :product_scopes, :dependent => :destroy
    accepts_nested_attributes_for :product_scopes

    has_many :promotion_rules

    make_permalink

    # Testing utility: creates new *ProductGroup* from search permalink url.
    # Follows conventions for accessing PGs from URLs, as decoded in routes
    def self.from_url(url)
      pg = nil;
      case url
      when /\/t\/(.+?)\/s\/(.+)/  then taxons = $1; attrs = $2;
      when /\/t\/(.+?)\/pg\/(.+)/ then taxons = $1; pg_name = $2;
      when /(.*?)\/s\/(.+)/       then attrs = $2;
      when /(.*?)\/pg\/(.+)/      then pg_name = $2;
      else                        return(nil)
      end

      if pg_name && opg = ProductGroup.find_by_permalink(pg_name)
        pg = new.from_product_group(opg)
      elsif attrs
        attrs = url.split('/')
        pg = new.from_route(attrs)
      end
      taxon = taxons && taxons.split('/').last
      pg.add_scope('in_taxon', taxon) if taxon

      pg
    end

    def from_product_group(opg)
      self.product_scopes = opg.product_scopes.map{|ps|
        ps = ps.clone;
        ps.product_group_id = nil;
        ps.product_group = self;
        ps
      }
      self
    end

    def from_route(attrs)
      self.order_scope = attrs.pop if attrs.length % 2 == 1
      attrs.each_slice(2) do |scope|
        next unless Product.respond_to?(scope.first)
        add_scope(scope.first, scope.last.split(','))
      end
      self
    end

    def from_search(search_hash)
      search_hash.each_pair do |scope_name, scope_attribute|
        add_scope(scope_name, scope_attribute)
      end

      self
    end

    def add_scope(scope_name, arguments=[])
      if scope_name.to_s !~ /eval|send|system|[^a-z0-9_!?]/
        self.product_scopes << ProductScope.new({
            :name => scope_name.to_s,
            :arguments => [*arguments]
          })
      else
        raise ArgumentError.new("'#{scope_name}` can't be used as scope")
      end
      self
    end

    def apply_on(scopish, use_order = true)
      # There's bug in AR, it doesn't merge :order, instead it takes order
      # from first nested_scope so we have to apply ordering FIRST.
      # see #2253 on rails LH
      base_product_scope = scopish
      if use_order && !self.order_scope.blank? && Product.respond_to?(self.order_scope.intern)
        base_product_scope = base_product_scope.send(self.order_scope)
      end

      return self.product_scopes.reject { |s| s.is_ordering? }.inject(base_product_scope) do |result, scope|
        scope.apply_on(result)
      end

    end

    # returns chain of named scopes generated from order scope and product scopes.
    def dynamic_products(use_order = true)
      apply_on(Product.group_by_products_id, use_order)
    end

    # Does the final ordering if requested
    # TODO: move the order stuff out of the above - is superfluous now
    def products(use_order = true)
      cached_group = Product.in_cached_group(self)
      if cached_group.limit(1).blank?
        dynamic_products(use_order)
      elsif !use_order
        cached_group
      else
        product_scopes.select { |s|
          s.is_ordering?
        }.inject(cached_group) { |res,order|
          order.apply_on(res)
        }
      end
    end

    def include?(product)
      res = apply_on(Product.where(:id => product.id), false)
      res.count > 0
    end

    def scopes_to_hash
      result = {}
      self.product_scopes.each do |scope|
        result[scope.name] = scope.arguments
      end
      result
    end

    def to_param
      permalink.present? ? permalink : (permalink_was || name.to_s.to_url)
    end

    def update_memberships
      # wipe everything directly to avoid expensive in-rails sorting
      ActiveRecord::Base.connection.execute "DELETE FROM spree_product_groups_products WHERE product_group_id = #{self.id}"

      # and generate the new group entirely in SQL
      ActiveRecord::Base.connection.execute "INSERT INTO spree_product_groups_products #{dynamic_products(false).scoped(:select => "spree_products.id, #{self.id}").to_sql}"
    end

    def generate_preview(size = Spree::Config[:admin_pgroup_per_page])
      count = self.class.count_by_sql ["SELECT COUNT(*) FROM spree_product_groups_products WHERE spree_product_groups_products.product_group_id = ?", self]

      return count, products.limit(size)
    end

    def to_s
      "<Spree::ProductGroup" + (id && "[#{id}]").to_s + ":'#{to_url}'>"
    end


    def order_scope
      if scope = product_scopes.detect {|s| s.is_ordering?}
        scope.name
      end
    end

    def order_scope=(scope_name)
      if scope = product_scopes.detect {|s| s.is_ordering?}
        scope.update_attribute(:name, scope_name)
      else
        self.product_scopes.build(:name => scope_name, :arguments => [])
      end
    end

    # Build a new product group with a scope to filter by specified products
    def self.new_from_products(products, attrs = {})
      pg = new(attrs)
      pg.product_scopes.build(:name => 'with_ids', :arguments => [products.map(&:id).join(',')])
      pg
    end
  end
end

app/controllers/spree/admin/product_groups_controller.rb
module Spree
  module Admin
    class ProductGroupsController < ResourceController
      before_filter :patch_params, :only => [:update]
  
      def preview
        @product_group = ProductGroup.new(params[:product_group])
        @product_group.name = "for_preview"
        respond_with(@product_group) { |format| format.html { render :partial => 'preview', :layout => false } }
      end

      protected

        def find_resource
          ProductGroup.find_by_permalink!(params[:id])
        end
     
        def location_after_save
          edit_admin_product_group_path(@product_group)
        end

        def collection
          params[:q] ||= {}
          params[:q][:sort] ||= "name.asc"
          @search = super.search(params[:q])
          @collection = @search.result(:distinct => true).page(params[:page]).per(Spree::Config[:admin_pgroup_per_page])
        end
    
      private

        # Consolidate argument arrays for nested product_scope attributes
        # Necessary for product scopes with multiple arguments
        def patch_params
          if params["product_group"] and params["product_group"]["product_scopes_attributes"].is_a?(Array)
            params["product_group"]["product_scopes_attributes"] = params["product_group"]["product_scopes_attributes"].group_by {|a| a["id"]}.map do |scope_id, attrs|
              a = { "id" => scope_id, "arguments" => attrs.map{|a| a["arguments"] }.flatten }
              if name = attrs.first["name"]
                a["name"] = name
              end
              a
            end
          end
        end



    end
  end
end

app/helpers/spree/admin/product_groups_helper.rb
module Spree
  module Admin
    module ProductGroupsHelper
      # Allow certain scope attributes to have a custom field type
      def product_scope_field(product_scope, i)
        value = (product_scope.arguments || [])[i]
        name = 'product_group[product_scopes_attributes][][arguments][]'
        if product_scope.name.to_sym == :with_ids
          text_field_tag name, value, :class => 'product_picker'
        else
          text_field_tag name, value
        end
      end
    end
  end
end

app/views/spree/admin/product_groups/_preview.html.erb
<% count, preview = @product_group.generate_preview(Spree::Config[:admin_pgroup_per_page]) %>

<h2><%= Spree::ProductGroup.human_attribute_name(:products) %> (<%= count %>)</h2>

<% if count == 0 %>
  <p data-hook="preview_empty"><%= Spree.t(:no_match_found) %></p>
<% else %>

  <% if count > Spree::Config[:admin_pgroup_per_page] %>
    <p data-hook="preview_showing"><%= Spree.t(:showing_first_n, :n => Spree::Config[:admin_pgroup_per_page]) %></p>
  <% end %>

  <table class="index" data-hook="preview">
    <thead>
      <tr data-hook="preview_header">
        <th><%= Spree::Product.human_attribute_name(:name) %></th>
        <th><%= Spree.t(:action) %></th>
      </tr>
    </thead>
    <tbody>
    <% preview.each do |product| %>
      <tr data-hook="preview_row">
        <td>
          <%= link_to product.name, product_url(product) %>
        </td>
        <td>
          <%= link_to Spree.t(:edit), edit_admin_product_path(product) %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>

app/views/spree/admin/product_groups/_product_scope.html.erb
<tr id="<%= dom_id product_scope %>" data-hook="product_scope">
  <td data-hook="description">
    <%= label_tag nil, t(:name, :scope => [:product_scopes, :scopes, product_scope.name]) %>
    <% if description = t(:description, :scope => [:product_scopes, :scopes, product_scope.name], :default => "") and description.present? %>
      <br /><%= description %>
    <% end %>
  </td>
  <td data-hook="arguments">
    <% if arguments = Spree::ProductScope.arguments_for_scope_name(product_scope.name.strip) %>
      <table><tr>
      <% arguments.each_with_index do |argument, i| %>
        <td>
          <%= label_tag nil, t(argument, :scope => [:product_scopes, :scopes, product_scope.name, :args]) %><br />
          <%= hidden_field_tag 'product_group[product_scopes_attributes][][id]', product_scope.id %>
          <%= product_scope_field product_scope, i %>
        </td>
      <% end %>
      </tr></table>
    <% end %>
  </td>
  <td class="actions" data-hook="actions">
    <%= link_to_delete product_scope, url: admin_product_group_product_scope_path(@product_group, product_scope), :no_text => true %>
  </td>
</tr>

app/views/spree/admin/product_groups/create.js.erb
$('#product_scopes').append('<%= escape_javascript( render('spree/admin/product_groups/product_scope', :product_scope => @product_scope) ) %>');
$('#<%= dom_id @product_scope %>').hide();
$('#<%= dom_id @product_scope %>').fadeIn();
if(!$('.token-input-list').is('*')){
  $('.tokeninput.products').productPicker();
}

app/views/spree/admin/product_groups/destroy.js.erb
$('#<%= dom_id @product_scope %>').fadeOut();
$('#<%= dom_id @product_scope %>').remove();
$('#preview_container').html('<%= escape_javascript( render('spree/admin/product_groups/preview') ) %>');

app/views/spree/admin/product_groups/edit.html.erb
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<h1><%= t(:editing_product_group) %></h1>

<fieldset id="product_group_forms_container" data-hook>

  <%= form_for [:admin, @product_group], :html => { :id => 'product-group-form', :method => :put } do |f| %>

      <%= f.field_container :name do %>
        <%= f.label :name, t(:name) %><br />
        <%= f.text_field :name %>
        <%= f.error_message_on :name %>
      <% end %>

      <%= f.field_container :permalink do %>
        <%= f.label :permalink, t(:permalink) %><br />
        <%= f.text_field :permalink %>
        <%= f.error_message_on :permalink %>
      <% end %>

      <%= f.field_container :order_scope do %>
        <%= f.label :order_scope, t(:sort_ordering) %><br />
        <%= f.select(:order_scope, Spree::Product.simple_scopes.collect{|p| [ t(:name, :scope =>[:product_scopes, :scopes, p]), p.to_s ] }) %>
      <% end %>

      <table id="product_scopes" data-hook>
        <%= render :partial => 'product_scope', :collection => @product_group.product_scopes.reject {|s| s.is_ordering? } %>
      </table>

    <%= button t(:update) %>

  <% end %>

  <%= form_tag admin_product_group_product_scopes_path(@product_group), :remote => true, :id => 'new_product_group_form' do %>
    <%
    options =
    grouped_options_for_select(
    Spree::ProductScope.all_scopes.map do |group_name, scopes|
      [
        t(:name, :scope => [:product_scopes, :groups, group_name]),
        scopes.keys.map do |scope_name|
          [ t(:name, :scope => [:product_scopes, :scopes, scope_name]), scope_name]
        end
      ]
    end
    )
    %>
    <p>
      <%= label_tag :product_scope_name, t(:add_scope) %>
      <%= select_tag 'product_scope[name]', options %>
      <%= submit_tag Spree.t(:add) %>
    </p>
  <% end %>

</fieldset>

<fieldset id="preview_container" data-hook>
  <%= render :partial => 'preview' %>
</fieldset>

app/views/spree/admin/product_groups/index.html.erb
<% render :partial => 'spree/admin/shared/product_sub_menu' %>

<% content_for :page_title do %>
  <%= Spree.t(:product_groups) %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to Spree.t(:new_product_group), new_object_url, :icon => 'icon-plus', :id => 'admin_new_product_group_link' %>
  </li>
<% end %>

<% if @product_groups.any? %>
  <table class="index" id='listing_product_groups' data-hook>
    <colgroup>
      <col style="width: 25%">
      <col style="width: 25%">
      <col style="width: 25%">
      <col style="width: 15%">
      <col style="width: 20%">
    </colgroup>
    <thead>
      <tr data-hook="product_group_header">
        <th><%= Spree::ProductGroup.human_attribute_name(:name) %></th>
        <th><%= Spree::ProductGroup.human_attribute_name(:url) %></th>
        <th><%= Spree::ProductGroup.human_attribute_name(:product_scopes) %></th>
        <th><%= Spree::ProductGroup.human_attribute_name(:product_count) %></th>
        <th><%= Spree.t(:action) %></th>
      </tr>
    </thead>
    <tbody>
      <% @product_groups.each do |pg| %>
        <tr id="<%= dom_id pg %>" data-hook="product_group_row" class="<%= cycle('odd', 'even')%>">
          <td class="align-center"><%= link_to pg.name, [:admin, pg] %></td>
          <td class="align-center"><%= link_to pg_search_path(:product_group_name => pg.permalink), pg_search_path(:product_group_name => pg.permalink) %></td>
          <td class="align-center"><%== pg.product_scopes.map(&:to_sentence).join('<br />') %></td>
          <td class="align-center"><%= pg.products.count %></td>
          <td data-hook="admin_recurrings_index_row_actions" class="actions">
            <%= link_to_edit pg, :no_text => true %>
            <%= link_to_delete pg, :no_text => true  %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate @product_groups %>
<% else %>
  <div class="alpha twelve columns no-objects-found">
    <%= Spree.t(:no_resource_found, resource: I18n.t(:other, scope: 'activerecord.models.spree/product_group')) %>,
    <%= link_to Spree.t(:add_one), new_object_url %>!
  </div>
<% end %>

app/views/spree/admin/product_groups/new.html.erb
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<% content_for :page_title do %>
  <%= Spree.t(:new_product_group) %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to Spree.t(:back_to_product_groups_list), admin_product_groups_url, :icon => 'icon-arrow-left' %>
  </li>
<% end %>

<%= form_for [:admin, @product_group], :html => { :id => 'product-group-form', :multipart => true } do |f| %>
  <fieldset data-hook="name">
    <legend><%= Spree::ProductGroup.model_name.human %></legend>
    <%= f.field_container :name do %>
      <%= f.label :name, Spree::ProductGroup.human_attribute_name(:name) %>
      <%= f.text_field :name %>
      <%= f.error_message_on :name %>
    <% end %>
  </fieldset>
  <%=  button Spree.t(:create) %>
<% end %>

app/views/spree/admin/product_groups/show.html.erb
<% render :partial => 'spree/admin/shared/product_sub_menu' %>
<h2><%= Spree::ProductGroup.model_name.human %></h2>
<p>
  <%= Spree::ProductGroup.human_attribute_name(:name) %>: <%= @product_group.name %>
</p>
<p>
  <%= Spree::ProductGroup.human_attribute_name(:url) %>: <%= link_to @product_group.permalink, "/pg/#{@product_group.permalink}" %>
</p>

<h2><%= Spree::ProductGroup.human_attribute_name(:product_scopes) %>(<%= @product_group.product_scopes.count %>)</h2>
<table class="product-scopes" data-hook="product_scopes">
  <thead>
    <tr data-hook="product_scopes_header">
      <th><%= Spree::ProductScope.human_attribute_name(:description) %></th>
      <th><%= Spree::ProductScope.human_attribute_name(:arguments) %></th>
    </tr>
  </thead>
  <tbody>
    <% @product_group.product_scopes.each do |product_scope| %>
      <tr <%= !product_scope.valid? ? "class='invalid'":'' %> data-hook="product_scopes_row">
        <td>
          <%= product_scope.to_sentence.html_safe %>
        </td>
        <td>
          <%= product_scope.arguments.join(', ') %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= render :partial => 'preview.html' %>